### ISSUE TITLE
Inference on pre-trained model

### ISSUE THREAD

**Issue by Parag0506** [dessa-public/fake-voice-detection#11]
Hello, Can anyone help me understand the inference logic used in the code? 
I used the pre-trained model and I can't seem to get correct results. No video is crossing the probability of 10% while classifying any audio file. What does the model prediction actually output? 
what does [[0.00045425]] mean? 

![image](https://user-images.githubusercontent.com/49458848/87872534-0d820d80-c9d7-11ea-9433-deb83607095a.png)

**Comment by ranasac19878** [comment]
Hi Parag, thanks for your inquiry. The pretrained model works good for the training and validation data. It is currently not working good for arbitrary audio files. We are working to improve the model currently and will release the new pretrained model soon. 

As of now, the model seems to predict low probabilities since the original training data had class imbalance (fake data was around 90% of total data).

Thanks,
Sachin
